name: Continuous Integration

on:
  pull_request:
    paths-ignore: "**/*.md"

  push:
    branches:
      - main
    paths-ignore: "**/*.md"

jobs:
  cancel-previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  checks:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    strategy:
      matrix:
        version: ["3.10", "3.11-dev"]

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt

      - name: Test
        run: ./test.sh

  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    strategy:
      matrix:
        version: ["3.10", "3.11-dev"]

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt

      - name: Lint
        run: ./lint.sh

  install:
    name: Install as library
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    strategy:
      matrix:
        version: ["3.10", "3.11-dev"]

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: pip install .
